services:
  user_service:
    class: InstitutoAtlanticoBundle\Service\UserService
    arguments: ["@doctrine.orm.entity_manager"]

  movie_service:
    class: InstitutoAtlanticoBundle\Service\MovieService
    arguments: ["@doctrine.orm.entity_manager"]

  rating_service:
    class: InstitutoAtlanticoBundle\Service\RatingService
    arguments: ["@doctrine.orm.entity_manager"]