services:
#    instituto_atlantico.example:
#        class: InstitutoAtlanticoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  user_service:
    class: InstitutoAtlanticoBundle\Service\UserService
    arguments: ["@doctrine.orm.entity_manager"]

  movie_service:
    class: InstitutoAtlanticoBundle\Service\MovieService
    arguments: ["@doctrine.orm.entity_manager"]