<?php

namespace InstitutoAtlanticoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use InstitutoAtlanticoBundle\Entity\Movie;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function persist(Movie $movie)
    {
        $this->getEntityManager()->persist($movie);
        $this->getEntityManager()->flush();
        return $movie;
    }

    public function remove(Movie $movie)
    {
        $this->getEntityManager()->remove($movie);
        $this->getEntityManager()->flush();
        return null;
    }
}
