<?php

namespace InstitutoAtlanticoBundle\Repository;

use InstitutoAtlanticoBundle\Entity\Recommendation;

/**
 * RecommendationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendationRepository extends \Doctrine\ORM\EntityRepository
{
    public function persist(Recommendation $recommendation)
    {
        $this->getEntityManager()->persist($recommendation);
    }

    public function flush()
    {
        $this->getEntityManager()->flush();
    }
}
